CC = gcc
FLAGS =  I.
OUT = ../../out
person:
	${CC} person.c -o ${OUT}/person
init:
	${CC} init.c -o ${OUT}/init

copy:
	${CC} copy.c -o ${OUT}/copy
union:
	${CC} union.c -o ${OUT}/union
enum:
	${CC} enum.c -o ${OUT}/enum
typedef:
	${CC} typedef.c -o ${OUT}/typedef
typedefwithstruct:
	${CC} typedefwithstruct.c -o ${OUT}/typedefwithstruct
typedefwithstruct2:
	${CC} typedefwithstruct2.c -o ${OUT}/typedefwithstruct2