CC = gcc
FLAGS =  I.
OUT = ../../out
fgets:
	${CC} fgets.c -o ${OUT}/fgets

gets:
	${CC} gets.c -o ${OUT}/gets

fputs:
	${CC} fputs.c -o ${OUT}/fputs
strlen:
	${CC} strlen.c -o ${OUT}/strlen

strcpy:
	${CC} strcpy.c -o ${OUT}/strcpy
strcat:
	${CC} strcat.c -o ${OUT}/strcat
strcmp:
	${CC} strcmp.c -o ${OUT}/strcmp